= Zeiterfassung für Gruppe 5

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Jannes |Prit |Philipp |Vihar |Pascal |Meeting
|1  |120   |120    |120    |150    |120    |180       
|2  |600   |120    |120    |660    |450    |180        
|3  |120   |60   |120    |120    |150    |180
|4  |300  |150   |480    |120    |370    |180
|5  |180 |360    |240    |120    |280    |180
|6  |90   |60   |60    |150    |200    |180        
|7  |180   |120    |180    |200    |120   |180        
|8  |720   |720   |720    |800    |750    |180
|9  |600  |600    |315    |600    |570    |180
|10  |90  |60   |100    |240    |210   |180
|11  |180  |180    |240    |180    |210   |180
|12  |240  |180    |120    |120    |180   |180
|13  |180   |180   |480    |600    |300   |180
|Nachbereitung |600   |…    |320    |120    |300   |180
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
