= Zeiterfassung für Gruppe 5

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Jannes |Prit |Philipp |Vihar |Pascal |Meeting
|1  |120   |120    |120    |150    |120    |380       
|2  |600   |120    |120    |660    |450    |380        
|3  |120   |60   |120    |120    |150    |380
|4  |300  |150   |480    |120    |370    |380
|5  |180 |360    |240    |120    |280    |380
|6  |90   |60   |60    |150    |200    |380        
|7  |180   |120    |180    |200    |120   |380        
|8  |720   |720   |720    |800    |750    |380
|9  |600  |600    |315    |600    |570    |380
|10  |90  |60   |100    |240    |210   |380
|11  |180  |180    |240    |180    |210   |380
|12  |240  |180    |120    |120    |180   |380
|13  |180   |180   |480    |600    |300   |380
|Nachbereitung |600   |180    |320    |120    |300   |380
|===
= Zeiterfassung für Gruppe 5


== Berechnungen

=== Summe der Arbeitsstunden pro Student

[options="header"]
|===
|Student |Summe (Stunden)
|Jannes |60.00
|Prit |48.50
|Philipp |54.92
|Vihar |67.67
|Pascal |65.17
|===

=== Arbeitsstunden pro Woche pro Student (inklusive Nachbereitung)

[options="header"]
|===
|Student |Stunden pro Woche
|Jannes |5.38
|Prit |3.96
|Philipp |4.63
|Vihar |5.36
|Pascal |5.41
|===

=== Durchschnittliche Arbeitszeit aller Studenten pro Woche

Die durchschnittliche Arbeitszeit aller Studenten pro Woche beträgt 4.55 Stunden.

== Formeln

* Summe der Arbeitsstunden pro Student: `SUMME(SPALTE(DevX)) / 60`
* Arbeitsstunden pro Woche pro Student: `(SUMME(SPALTE(DevX)) + Nachbereitung) / 13 / 60`
* Durchschnittliche Arbeitzeit aller Studenten pro Woche: `(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5))) / (5 * 13) / 60`

NOTE: Alle Zeiten wurden von Minuten in Stunden umgerechnet.
Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
